import operator
from typing import Annotated, List, Dict, Any, Literal
from typing_extensions import TypedDict
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

class AgentState(TypedDict):
    """
    State object for the travel agent.
    TypedDict is used for compatibility with LangGraph checkpointers.
    """

    # --- Conversation Context ---
    # Annotated with add_messages so new messages append to the list automatically
    messages: Annotated[List[BaseMessage], add_messages]

    # --- Rewrite & Routing Layer ---
    # The search-optimized version of the user's request
    rewritten_query: str

    # Safety flag to stop the graph if content is harmful
    is_safe: bool

    # Flag to trigger the human_interrupter node
    is_incomplete: bool

    # Classification: 'quick' for simple QA, 'planner' for full trip planning
    mode: Literal["quick", "planner"]

    # --- Planning & Research Data ---
    # List of sub-queries generated by the Planner (Flights, Hotels, Transport)
    plan: List[str]

    # Raw research data collected from search tools
    research_data: Annotated[List[str], operator.add]

    # --- Final Artifacts ---
    # Structured JSON for UI rendering (contains Flight details, Stay options, etc.)
    itinerary_artifact: Dict[str, Any]

    # --- User Memory ---
    # Persistent preferences (e.g., "Always prefers bike rentals over cabs")
    user_profile: Dict[str, Any]